
BEGIN ORIGINAL SCREEN_STYLES.CSS
.promo.four { background-repeat: no-repeat; background-size: 980px 715px; background-image: url(https://icons.wxug.com/data/weather-maps/radar/united-states/salina-kansas-region-current-radar-animation.gif); }
.promo.five { background-repeat: no-repeat; background-size: 980px 715px; background-image: url(https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=SGF&brand=wui&num=10&delay=15&type=N0R&frame=0&scale=0.125&noclutter=1&showstorms=0&mapx=400&mapy=240&centerx=382&centery=567&transx=-18&transy=327&showlabels=1&severe=0&rainsnow=1&lightning=0&smooth=1&rand=25127676&lat=0&lon=0&label=you); }
END ORIGINAL SCREEN_STYLES.CSS


BEGIN ORIGINAL CSS STYLES

@media only screen and (max-width:750px){article{padding:1em 0 0 0}header{display:none}article h1{display:none}.navrule1{display:none}
.promo_container .promo.three {
	width:450px;
	margin: 0 auto;
	float: none;
	display: block;
}
nav {
	display: block;
	position: static;
	padding: 10px 0px 10px 10px;
	background-color: #515673;
}
}
@media only screen and (max-width:430px){
.promo_container .promo.three {
	width: 400px;
	margin: 0 auto;
	float: none;
}	
}

.promo_container .promo.two img {
	width: 128px;
}	
.promo_container .promo.three, {
	width: 473px;
	display: block;
	margin: 0 auto;
}
.promo_container .promo.four img {
	width: 940px;
}	
.promo_container .promo.five img {
	width: 940px;
}	

/* ARTICLE PADDING.  PLACE THE ARTICLE BELOW THE NAVIGATION */
@media only screen and (min-width:749px) and (max-width:890px){article{padding:17em 0 0 0;text-align:center}}
@media only screen and (min-width:891px){article{padding:14em 0 0 0;text-align:center}}
@media only screen and (min-width:810px){.promo.three{display:none}}
@media only screen and (max-width:810px){.promo.seven{display:none}}
@media screen and (orientation:portrait){.promo.three{display:none}}
@media screen and (orientation:landscape){.promo.six{display:none}}

END ORIGINAL CSS STYLES














BELOW ARE CHANGES MADE BEFORE BREAKPOINT FOR ZTE N817

.promo_container .promo.six img {
	width: 473px;
}


.promo_container .promo.six img {
	width: 315px;
}
.promo_container .promo.six img {
	width: 473px;
}

 width=473 height=196

.promo_container .promo.four img {
	width: 940px;
}	
// width=940px height=715px 
// #fixed-width-flamingo {  width: 500px; }


.promo_container .promo.two img {
	width: 128px;
}	
 width=128 height=196
 
 .promo_container .promo.three img {
	width: 473px;
}
 width="100%" height="196"